# Flink configuration file

# JobManager configuration
jobmanager.rpc.address: localhost
jobmanager.rpc.port: 6123
jobmanager.heap.size: 1024m
jobmanager.rpc.numThreads: 8

# TaskManager configuration
taskmanager.memory.process.size: 1024m
taskmanager.memory.managed.size: 768m
taskmanager.numberOfTaskSlots: 2
taskmanager.rpc.numThreads: 8

# High Availability configuration
high-availability: zookeeper
high-availability.storageDir: hdfs://localhost:9000/flink/recovery
high-availability.zookeeper.quorum: localhost:2181
high-availability.zookeeper.path.root: /flink

# Parallelism and resource allocation
parallelism.default: 2
parallelism.max: 8
taskmanager.cpu.cores: 4

# State backend configuration
state.backend: rocksdb
state.checkpoints.dir: hdfs://localhost:9000/flink/checkpoints
state.backend.rocksdb.memory.managed: true
state.backend.rocksdb.predefined-options: FLASH_SSD_OPTIMIZED

# Logging configuration
log4j.logger.org.apache.flink: INFO,console
log4j.logger.org.apache.flink.client.cli: INFO,console
log4j.logger.org.apache.flink.runtime.rest: INFO,console
log4j.logger.org.apache.flink.runtime.rpc: INFO,console
